Sordid-Arrays/Turntify

middlewares/echonest.js
Managed to get danceability from Echo Nest
=> (feat) get danceability from Echo Nest

middlewares/echonest.js
getTrackData takes array of URIs and returns array of data of songs
=> (refactor) getTrackData accept array of spotify ids

tests/server/api/echonestSpec.js
=> (test) echonest.getTrackData

tests/server/api/echonestSpec.js
added a test for multiple songs
=> (test) added test for multiple songs

middlewares/echonest.js, package.json
=> (feat) echonest returns spotify uris

controllers/index.js, helpers/util.js, middlewares/spotify.js
moved generateRandomString to helpers/util.js
moved spotify api request into middlewares/spotify.js
=> (refactor) separated util functions to another file

controllers/index.js
Sorry, forgot to commit some changes.
=> (refactor) moved generateRandomString to util.js

controllers/index.js, middlewares/spotify.js
(refactor) refresh token if it is expired
=> (refactor) refresh token if it is expired

middlewares/spotify.js
=> (fix) include owner id of playlists

middlewares/spotify.js, tests/server/api/spotifySpec.js
=> (test) Moved getTestingToken to spec file

public/app/player/player.html, public/app/player/player.js, public/app/player/playerServices.js
=> [refactor] Clean up player controller/svcs in reasonable manner

helpers/util.js, routes/auth.js, routes/player.js
fixed to save session every time token is refreshed
=> (fix) new token was not saved in session

middlewares/spotify.js, package.json, routes/auth.js, routes/player.js, tests/server/api/spotifySpec.js
deleted unnecessary dependencies
=> (refactor) clean up

middlewares/echonest.js, routes/auth.js, routes/player.js
=> (refactor) return response with 500 on server error

helpers/util.js, middlewares/echonest.js, routes/player.js
filtering playlist songs according to dancceability in util.js
=> (refactor) move filtering logic to helpers

tests/server/helpers/utilSpec.js
=> (test) add test for helper functions

middlewares/echonest.js
we should have used request-promise...
=> (refactor) use request-promise

middlewares/spotify.js, tests/server/api/echonestSpec.js, tests/server/api/spotifySpec.js
request-promise also in api/spotify.js
=> (refactor) use request-promise in api/spotify.js

helpers/util.js, tests/server/api/spotifySpec.js, tests/server/helpers/utilSpec.js
=> [feat] user can select from 11 turntness

karma.conf.js, public/app/player/player.test.js
and assign dummy selected playlist in test
=> [test] load angular-material files in karma.conf

README.md
we don't need to install and run mongodb on local
=> [doc] delete mongodb from readme

helpers/playlistHelper.js, routes/player.js
make API requests synchronously
=> [refactor] optimize api requests

routes/player.js
=> [fix] merge mistake

middlewares/spotify.js, public/app/app.js, public/app/search/search.html, public/app/search/search.js, public/app/search/searchService.js, public/app/services/requests.js, public/index.html
just showing the songs in text area for now.
we need to let users select one and pass it to player view.
searching result is not good... we might need to implement a better algorithm...?
=> [feat] type to search for songs

helpers/util.js, public/app/search/search.html, routes/player.js
escape search words in back-end
=> [fix] Escape for regular expression

public/app/search/search.html, routes/player.js
=> [fix] Search returns songs which contains all search words

public/app/search/search.js
don't update view if the search box is different from what it was
=> [fix] dealing with timelag of each search requests

helpers/playlistHelper.js
fix arguments on refreshing token
=> [fix] on refresh token, arguments were wrong

public/app/search/searchService.js, public/app/services/requests.js, routes/player.js
search box is now working with artist name
=> [feat] make search box working

helpers/playlistHelper.js, middlewares/echonest.js, routes/player.js
1) get number of songs
2) make API requests for each 100 songs until we get all songs
=> [fix] call Echo Nest API multiple times

routes/auth.js, routes/player.js
And deleted functions which are no longer used
=> [refactor] consistency in error handling, deleted functions which are no longer used

public/app/player/playerServices.js, public/app/search/search.html, public/app/search/search.js, public/app/search/searchService.js, public/assets/css/app.css
please fix the styling(colors) to fit to other parts...
=> [feat] select candidate with up/down key

public/app/player/player.html, public/app/player/playerServices.js, public/app/search/search.js
I changed ng-model of checkbox because I want to check it from PlayerService and it seems you are not using player.checked anywhere else.
Please double check it.
=> [fix] minor bugs

routes/auth.js
At line 96, user was null if the user was not in database (i.e. the first login to this app)
=> [fix] save session before db access

public/app/player/playerServices.js, public/app/search/search.js
search for the Spotify ID of the artist in the list of playlists before add the playlist
=> [fix] do not add playlist of the artist if it already exists

helpers/playlistHelper.js, middlewares/echonest.js, routes/player.js
when hit the API limit, 
1) send response with status code 429
2) send back the song data from Ghettonest
=> [feat] send back 429 error when hit the echonest limit

helpers/playlistHelper.js
filter dbSongs before send back
do not concat makeUpGhettonest
=> [fix] do not send back unknown Ghettonests

public/app/app.js, public/app/match_params/matchParams.js, public/app/player/player.html, public/app/search/search.html, public/app/search/search.js, public/assets/css/app.css
convert match-params sub-view to a directive
stylize artist search
initialize and stylize slider
=> [Feat] style playlist builder

helpers/playlistHelper.js, routes/player.js
=> [refactor] clean up

middlewares/spotify.js
It used to return only 20 playlists. Now it returns 50 playlists at most
=> [fix] return 50 playlists

public/app/search/search.html, public/app/search/search.js, public/app/search/searchService.js
[public/app/search/search.js  line 22~ ]
$location.hash('searchArtist') will just append "#searchArtist" to address bar.
$anchorScroll() will actually scroll to that element.
I think it's less expensive than searching for "md-content.checkboxWrapper" in the DOM.
=> [fix] auto scroll works

helpers/playlistHelper.js
Just change private function name for clarity
=> [refactor] change function name

tests/server/api/spotifySpec.js
=> [test] fixed Spotify module test

public/app/custom_playlist/customPlaylist.html, public/app/custom_playlist/customPlaylist.js, public/app/player/player.html, public/app/player/playerServices.js, public/assets/css/app.css
made iframe larger w/ album art, changed wording of headers
=> [feat] playlist Iframe opens in modal

public/app/player/player.js, public/app/player/playerServices.js
on-screen error message was saying that no playlist was selected after loading an artist-based playlist
=> [fix] playlist count updates when adding artist-based playlist

public/app/player/player.js, public/app/player/player.test.js, public/app/player/playerServices.js, public/app/services/requests.js
* Player-controller and player-service tests
* Removed unused player-controller functions
=> [Feat] add karma tests

gulpfile.js, package.json
* task for running server tests
* task for running client tests
* task for running client and server tests
=> [feat] gulp test tasks

helpers/playlistHelper.js, middlewares/spotify.js, routes/player.js
* Post to spotify with JSON instead of query string
* Make multiple posts to spotify w/ 100 songs-max each time
=> [refactor] create large spotify playlist 

README.md, public/app/player/player.html, public/assets/css/app.css
* Also fixed bug where checkboxes all overlapped on ios & safari
=> [docs] add test-running to readme

gulpfile.js, package.json, public/assets/css/app.scss
* created sass file
* copied over origional css and refactored to use sass featured
* added sass-compile to gulp-styles task
=> [feat] sass file
